const CommandCore = require("../../handler/commandcore");
const { MessageEmbed } = require("discord.js");
const { get } = require("node-superfetch");
const cheerio = require("cheerio");

module.exports = class WaifuCommand extends CommandCore {
  constructor() {
    super({
      name: "waifu",
      description: "Generate a random waifu picture (generated by AI)",
      usage: "waifu",
      cooldown: 0,
      aliases: ["w"],
      devOnly: false,
      guildOnly: true,
      nsfw: false,
      clientPermission: [],
      authorPermission: []
    });
  }

  execute(client, message, args, thread) {
    const MIN = 0;
    const MAX = 199999;
    const randNum = Math.floor(Math.random() * (MAX - MIN + 1)) + MIN;

    const imageSource = `https://www.thiswaifudoesnotexist.net/example-${randNum}.jpg`;

    if (imageSource) {
      return message.channel.send(
        "Here is your random waifu (generated by AI)",
        {
          files: [imageSource]
        }
      );
    }

    return message.channel.send("Fetching Error! Please Try Again.");
  }
};
